// <auto-generated />
namespace MovieNetDbProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renameId_genrebis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameId_genrebis));
        
        string IMigrationMetadata.Id
        {
            get { return "201709151016195_renameId_genrebis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
